require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AttemptAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # AttemptAttribute. As you add validations to AttemptAttribute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AttemptAttributesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all attempt_attributes as @attempt_attributes" do
      attempt_attribute = AttemptAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:attempt_attributes).should eq([attempt_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested attempt_attribute as @attempt_attribute" do
      attempt_attribute = AttemptAttribute.create! valid_attributes
      get :show, {:id => attempt_attribute.to_param}, valid_session
      assigns(:attempt_attribute).should eq(attempt_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new attempt_attribute as @attempt_attribute" do
      get :new, {}, valid_session
      assigns(:attempt_attribute).should be_a_new(AttemptAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested attempt_attribute as @attempt_attribute" do
      attempt_attribute = AttemptAttribute.create! valid_attributes
      get :edit, {:id => attempt_attribute.to_param}, valid_session
      assigns(:attempt_attribute).should eq(attempt_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AttemptAttribute" do
        expect {
          post :create, {:attempt_attribute => valid_attributes}, valid_session
        }.to change(AttemptAttribute, :count).by(1)
      end

      it "assigns a newly created attempt_attribute as @attempt_attribute" do
        post :create, {:attempt_attribute => valid_attributes}, valid_session
        assigns(:attempt_attribute).should be_a(AttemptAttribute)
        assigns(:attempt_attribute).should be_persisted
      end

      it "redirects to the created attempt_attribute" do
        post :create, {:attempt_attribute => valid_attributes}, valid_session
        response.should redirect_to(AttemptAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved attempt_attribute as @attempt_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        AttemptAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:attempt_attribute => {}}, valid_session
        assigns(:attempt_attribute).should be_a_new(AttemptAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AttemptAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:attempt_attribute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested attempt_attribute" do
        attempt_attribute = AttemptAttribute.create! valid_attributes
        # Assuming there are no other attempt_attributes in the database, this
        # specifies that the AttemptAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AttemptAttribute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => attempt_attribute.to_param, :attempt_attribute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested attempt_attribute as @attempt_attribute" do
        attempt_attribute = AttemptAttribute.create! valid_attributes
        put :update, {:id => attempt_attribute.to_param, :attempt_attribute => valid_attributes}, valid_session
        assigns(:attempt_attribute).should eq(attempt_attribute)
      end

      it "redirects to the attempt_attribute" do
        attempt_attribute = AttemptAttribute.create! valid_attributes
        put :update, {:id => attempt_attribute.to_param, :attempt_attribute => valid_attributes}, valid_session
        response.should redirect_to(attempt_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the attempt_attribute as @attempt_attribute" do
        attempt_attribute = AttemptAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AttemptAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => attempt_attribute.to_param, :attempt_attribute => {}}, valid_session
        assigns(:attempt_attribute).should eq(attempt_attribute)
      end

      it "re-renders the 'edit' template" do
        attempt_attribute = AttemptAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AttemptAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => attempt_attribute.to_param, :attempt_attribute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested attempt_attribute" do
      attempt_attribute = AttemptAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => attempt_attribute.to_param}, valid_session
      }.to change(AttemptAttribute, :count).by(-1)
    end

    it "redirects to the attempt_attributes list" do
      attempt_attribute = AttemptAttribute.create! valid_attributes
      delete :destroy, {:id => attempt_attribute.to_param}, valid_session
      response.should redirect_to(attempt_attributes_url)
    end
  end

end
