require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IsoformsController do

  # This should return the minimal set of attributes required to create a valid
  # Isoform. As you add validations to Isoform, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IsoformsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all isoforms as @isoforms" do
      isoform = Isoform.create! valid_attributes
      get :index, {}, valid_session
      assigns(:isoforms).should eq([isoform])
    end
  end

  describe "GET show" do
    it "assigns the requested isoform as @isoform" do
      isoform = Isoform.create! valid_attributes
      get :show, {:id => isoform.to_param}, valid_session
      assigns(:isoform).should eq(isoform)
    end
  end

  describe "GET new" do
    it "assigns a new isoform as @isoform" do
      get :new, {}, valid_session
      assigns(:isoform).should be_a_new(Isoform)
    end
  end

  describe "GET edit" do
    it "assigns the requested isoform as @isoform" do
      isoform = Isoform.create! valid_attributes
      get :edit, {:id => isoform.to_param}, valid_session
      assigns(:isoform).should eq(isoform)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Isoform" do
        expect {
          post :create, {:isoform => valid_attributes}, valid_session
        }.to change(Isoform, :count).by(1)
      end

      it "assigns a newly created isoform as @isoform" do
        post :create, {:isoform => valid_attributes}, valid_session
        assigns(:isoform).should be_a(Isoform)
        assigns(:isoform).should be_persisted
      end

      it "redirects to the created isoform" do
        post :create, {:isoform => valid_attributes}, valid_session
        response.should redirect_to(Isoform.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved isoform as @isoform" do
        # Trigger the behavior that occurs when invalid params are submitted
        Isoform.any_instance.stub(:save).and_return(false)
        post :create, {:isoform => {}}, valid_session
        assigns(:isoform).should be_a_new(Isoform)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Isoform.any_instance.stub(:save).and_return(false)
        post :create, {:isoform => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested isoform" do
        isoform = Isoform.create! valid_attributes
        # Assuming there are no other isoforms in the database, this
        # specifies that the Isoform created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Isoform.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => isoform.to_param, :isoform => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested isoform as @isoform" do
        isoform = Isoform.create! valid_attributes
        put :update, {:id => isoform.to_param, :isoform => valid_attributes}, valid_session
        assigns(:isoform).should eq(isoform)
      end

      it "redirects to the isoform" do
        isoform = Isoform.create! valid_attributes
        put :update, {:id => isoform.to_param, :isoform => valid_attributes}, valid_session
        response.should redirect_to(isoform)
      end
    end

    describe "with invalid params" do
      it "assigns the isoform as @isoform" do
        isoform = Isoform.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Isoform.any_instance.stub(:save).and_return(false)
        put :update, {:id => isoform.to_param, :isoform => {}}, valid_session
        assigns(:isoform).should eq(isoform)
      end

      it "re-renders the 'edit' template" do
        isoform = Isoform.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Isoform.any_instance.stub(:save).and_return(false)
        put :update, {:id => isoform.to_param, :isoform => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested isoform" do
      isoform = Isoform.create! valid_attributes
      expect {
        delete :destroy, {:id => isoform.to_param}, valid_session
      }.to change(Isoform, :count).by(-1)
    end

    it "redirects to the isoforms list" do
      isoform = Isoform.create! valid_attributes
      delete :destroy, {:id => isoform.to_param}, valid_session
      response.should redirect_to(isoforms_url)
    end
  end

end
