require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReagentTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ReagentType. As you add validations to ReagentType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReagentTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reagent_types as @reagent_types" do
      reagent_type = ReagentType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reagent_types).should eq([reagent_type])
    end
  end

  describe "GET show" do
    it "assigns the requested reagent_type as @reagent_type" do
      reagent_type = ReagentType.create! valid_attributes
      get :show, {:id => reagent_type.to_param}, valid_session
      assigns(:reagent_type).should eq(reagent_type)
    end
  end

  describe "GET new" do
    it "assigns a new reagent_type as @reagent_type" do
      get :new, {}, valid_session
      assigns(:reagent_type).should be_a_new(ReagentType)
    end
  end

  describe "GET edit" do
    it "assigns the requested reagent_type as @reagent_type" do
      reagent_type = ReagentType.create! valid_attributes
      get :edit, {:id => reagent_type.to_param}, valid_session
      assigns(:reagent_type).should eq(reagent_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReagentType" do
        expect {
          post :create, {:reagent_type => valid_attributes}, valid_session
        }.to change(ReagentType, :count).by(1)
      end

      it "assigns a newly created reagent_type as @reagent_type" do
        post :create, {:reagent_type => valid_attributes}, valid_session
        assigns(:reagent_type).should be_a(ReagentType)
        assigns(:reagent_type).should be_persisted
      end

      it "redirects to the created reagent_type" do
        post :create, {:reagent_type => valid_attributes}, valid_session
        response.should redirect_to(ReagentType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reagent_type as @reagent_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentType.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_type => {}}, valid_session
        assigns(:reagent_type).should be_a_new(ReagentType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentType.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reagent_type" do
        reagent_type = ReagentType.create! valid_attributes
        # Assuming there are no other reagent_types in the database, this
        # specifies that the ReagentType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReagentType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reagent_type.to_param, :reagent_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reagent_type as @reagent_type" do
        reagent_type = ReagentType.create! valid_attributes
        put :update, {:id => reagent_type.to_param, :reagent_type => valid_attributes}, valid_session
        assigns(:reagent_type).should eq(reagent_type)
      end

      it "redirects to the reagent_type" do
        reagent_type = ReagentType.create! valid_attributes
        put :update, {:id => reagent_type.to_param, :reagent_type => valid_attributes}, valid_session
        response.should redirect_to(reagent_type)
      end
    end

    describe "with invalid params" do
      it "assigns the reagent_type as @reagent_type" do
        reagent_type = ReagentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_type.to_param, :reagent_type => {}}, valid_session
        assigns(:reagent_type).should eq(reagent_type)
      end

      it "re-renders the 'edit' template" do
        reagent_type = ReagentType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentType.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_type.to_param, :reagent_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reagent_type" do
      reagent_type = ReagentType.create! valid_attributes
      expect {
        delete :destroy, {:id => reagent_type.to_param}, valid_session
      }.to change(ReagentType, :count).by(-1)
    end

    it "redirects to the reagent_types list" do
      reagent_type = ReagentType.create! valid_attributes
      delete :destroy, {:id => reagent_type.to_param}, valid_session
      response.should redirect_to(reagent_types_url)
    end
  end

end
