require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReagentValuesController do

  # This should return the minimal set of attributes required to create a valid
  # ReagentValue. As you add validations to ReagentValue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReagentValuesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reagent_values as @reagent_values" do
      reagent_value = ReagentValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reagent_values).should eq([reagent_value])
    end
  end

  describe "GET show" do
    it "assigns the requested reagent_value as @reagent_value" do
      reagent_value = ReagentValue.create! valid_attributes
      get :show, {:id => reagent_value.to_param}, valid_session
      assigns(:reagent_value).should eq(reagent_value)
    end
  end

  describe "GET new" do
    it "assigns a new reagent_value as @reagent_value" do
      get :new, {}, valid_session
      assigns(:reagent_value).should be_a_new(ReagentValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested reagent_value as @reagent_value" do
      reagent_value = ReagentValue.create! valid_attributes
      get :edit, {:id => reagent_value.to_param}, valid_session
      assigns(:reagent_value).should eq(reagent_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReagentValue" do
        expect {
          post :create, {:reagent_value => valid_attributes}, valid_session
        }.to change(ReagentValue, :count).by(1)
      end

      it "assigns a newly created reagent_value as @reagent_value" do
        post :create, {:reagent_value => valid_attributes}, valid_session
        assigns(:reagent_value).should be_a(ReagentValue)
        assigns(:reagent_value).should be_persisted
      end

      it "redirects to the created reagent_value" do
        post :create, {:reagent_value => valid_attributes}, valid_session
        response.should redirect_to(ReagentValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reagent_value as @reagent_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentValue.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_value => {}}, valid_session
        assigns(:reagent_value).should be_a_new(ReagentValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentValue.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_value => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reagent_value" do
        reagent_value = ReagentValue.create! valid_attributes
        # Assuming there are no other reagent_values in the database, this
        # specifies that the ReagentValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReagentValue.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reagent_value.to_param, :reagent_value => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reagent_value as @reagent_value" do
        reagent_value = ReagentValue.create! valid_attributes
        put :update, {:id => reagent_value.to_param, :reagent_value => valid_attributes}, valid_session
        assigns(:reagent_value).should eq(reagent_value)
      end

      it "redirects to the reagent_value" do
        reagent_value = ReagentValue.create! valid_attributes
        put :update, {:id => reagent_value.to_param, :reagent_value => valid_attributes}, valid_session
        response.should redirect_to(reagent_value)
      end
    end

    describe "with invalid params" do
      it "assigns the reagent_value as @reagent_value" do
        reagent_value = ReagentValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_value.to_param, :reagent_value => {}}, valid_session
        assigns(:reagent_value).should eq(reagent_value)
      end

      it "re-renders the 'edit' template" do
        reagent_value = ReagentValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_value.to_param, :reagent_value => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reagent_value" do
      reagent_value = ReagentValue.create! valid_attributes
      expect {
        delete :destroy, {:id => reagent_value.to_param}, valid_session
      }.to change(ReagentValue, :count).by(-1)
    end

    it "redirects to the reagent_values list" do
      reagent_value = ReagentValue.create! valid_attributes
      delete :destroy, {:id => reagent_value.to_param}, valid_session
      response.should redirect_to(reagent_values_url)
    end
  end

end
