require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReagentAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # ReagentAttribute. As you add validations to ReagentAttribute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReagentAttributesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reagent_attributes as @reagent_attributes" do
      reagent_attribute = ReagentAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reagent_attributes).should eq([reagent_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested reagent_attribute as @reagent_attribute" do
      reagent_attribute = ReagentAttribute.create! valid_attributes
      get :show, {:id => reagent_attribute.to_param}, valid_session
      assigns(:reagent_attribute).should eq(reagent_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new reagent_attribute as @reagent_attribute" do
      get :new, {}, valid_session
      assigns(:reagent_attribute).should be_a_new(ReagentAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested reagent_attribute as @reagent_attribute" do
      reagent_attribute = ReagentAttribute.create! valid_attributes
      get :edit, {:id => reagent_attribute.to_param}, valid_session
      assigns(:reagent_attribute).should eq(reagent_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReagentAttribute" do
        expect {
          post :create, {:reagent_attribute => valid_attributes}, valid_session
        }.to change(ReagentAttribute, :count).by(1)
      end

      it "assigns a newly created reagent_attribute as @reagent_attribute" do
        post :create, {:reagent_attribute => valid_attributes}, valid_session
        assigns(:reagent_attribute).should be_a(ReagentAttribute)
        assigns(:reagent_attribute).should be_persisted
      end

      it "redirects to the created reagent_attribute" do
        post :create, {:reagent_attribute => valid_attributes}, valid_session
        response.should redirect_to(ReagentAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reagent_attribute as @reagent_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_attribute => {}}, valid_session
        assigns(:reagent_attribute).should be_a_new(ReagentAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:reagent_attribute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reagent_attribute" do
        reagent_attribute = ReagentAttribute.create! valid_attributes
        # Assuming there are no other reagent_attributes in the database, this
        # specifies that the ReagentAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReagentAttribute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reagent_attribute.to_param, :reagent_attribute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reagent_attribute as @reagent_attribute" do
        reagent_attribute = ReagentAttribute.create! valid_attributes
        put :update, {:id => reagent_attribute.to_param, :reagent_attribute => valid_attributes}, valid_session
        assigns(:reagent_attribute).should eq(reagent_attribute)
      end

      it "redirects to the reagent_attribute" do
        reagent_attribute = ReagentAttribute.create! valid_attributes
        put :update, {:id => reagent_attribute.to_param, :reagent_attribute => valid_attributes}, valid_session
        response.should redirect_to(reagent_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the reagent_attribute as @reagent_attribute" do
        reagent_attribute = ReagentAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_attribute.to_param, :reagent_attribute => {}}, valid_session
        assigns(:reagent_attribute).should eq(reagent_attribute)
      end

      it "re-renders the 'edit' template" do
        reagent_attribute = ReagentAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReagentAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => reagent_attribute.to_param, :reagent_attribute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reagent_attribute" do
      reagent_attribute = ReagentAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => reagent_attribute.to_param}, valid_session
      }.to change(ReagentAttribute, :count).by(-1)
    end

    it "redirects to the reagent_attributes list" do
      reagent_attribute = ReagentAttribute.create! valid_attributes
      delete :destroy, {:id => reagent_attribute.to_param}, valid_session
      response.should redirect_to(reagent_attributes_url)
    end
  end

end
