require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TranscriptionFactorsController do

  # This should return the minimal set of attributes required to create a valid
  # TranscriptionFactor. As you add validations to TranscriptionFactor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TranscriptionFactorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all transcription_factors as @transcription_factors" do
      transcription_factor = TranscriptionFactor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transcription_factors).should eq([transcription_factor])
    end
  end

  describe "GET show" do
    it "assigns the requested transcription_factor as @transcription_factor" do
      transcription_factor = TranscriptionFactor.create! valid_attributes
      get :show, {:id => transcription_factor.to_param}, valid_session
      assigns(:transcription_factor).should eq(transcription_factor)
    end
  end

  describe "GET new" do
    it "assigns a new transcription_factor as @transcription_factor" do
      get :new, {}, valid_session
      assigns(:transcription_factor).should be_a_new(TranscriptionFactor)
    end
  end

  describe "GET edit" do
    it "assigns the requested transcription_factor as @transcription_factor" do
      transcription_factor = TranscriptionFactor.create! valid_attributes
      get :edit, {:id => transcription_factor.to_param}, valid_session
      assigns(:transcription_factor).should eq(transcription_factor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TranscriptionFactor" do
        expect {
          post :create, {:transcription_factor => valid_attributes}, valid_session
        }.to change(TranscriptionFactor, :count).by(1)
      end

      it "assigns a newly created transcription_factor as @transcription_factor" do
        post :create, {:transcription_factor => valid_attributes}, valid_session
        assigns(:transcription_factor).should be_a(TranscriptionFactor)
        assigns(:transcription_factor).should be_persisted
      end

      it "redirects to the created transcription_factor" do
        post :create, {:transcription_factor => valid_attributes}, valid_session
        response.should redirect_to(TranscriptionFactor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transcription_factor as @transcription_factor" do
        # Trigger the behavior that occurs when invalid params are submitted
        TranscriptionFactor.any_instance.stub(:save).and_return(false)
        post :create, {:transcription_factor => {}}, valid_session
        assigns(:transcription_factor).should be_a_new(TranscriptionFactor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TranscriptionFactor.any_instance.stub(:save).and_return(false)
        post :create, {:transcription_factor => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transcription_factor" do
        transcription_factor = TranscriptionFactor.create! valid_attributes
        # Assuming there are no other transcription_factors in the database, this
        # specifies that the TranscriptionFactor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TranscriptionFactor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => transcription_factor.to_param, :transcription_factor => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested transcription_factor as @transcription_factor" do
        transcription_factor = TranscriptionFactor.create! valid_attributes
        put :update, {:id => transcription_factor.to_param, :transcription_factor => valid_attributes}, valid_session
        assigns(:transcription_factor).should eq(transcription_factor)
      end

      it "redirects to the transcription_factor" do
        transcription_factor = TranscriptionFactor.create! valid_attributes
        put :update, {:id => transcription_factor.to_param, :transcription_factor => valid_attributes}, valid_session
        response.should redirect_to(transcription_factor)
      end
    end

    describe "with invalid params" do
      it "assigns the transcription_factor as @transcription_factor" do
        transcription_factor = TranscriptionFactor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TranscriptionFactor.any_instance.stub(:save).and_return(false)
        put :update, {:id => transcription_factor.to_param, :transcription_factor => {}}, valid_session
        assigns(:transcription_factor).should eq(transcription_factor)
      end

      it "re-renders the 'edit' template" do
        transcription_factor = TranscriptionFactor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TranscriptionFactor.any_instance.stub(:save).and_return(false)
        put :update, {:id => transcription_factor.to_param, :transcription_factor => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transcription_factor" do
      transcription_factor = TranscriptionFactor.create! valid_attributes
      expect {
        delete :destroy, {:id => transcription_factor.to_param}, valid_session
      }.to change(TranscriptionFactor, :count).by(-1)
    end

    it "redirects to the transcription_factors list" do
      transcription_factor = TranscriptionFactor.create! valid_attributes
      delete :destroy, {:id => transcription_factor.to_param}, valid_session
      response.should redirect_to(transcription_factors_url)
    end
  end

end
